const cfg=window.KH_SUPABASE||{};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let db=null;const MEDIA_BUCKET='site-media';const records={news:{},matches:{},players:{},sponsors:{}};
function status(text,error=false){const el=$('#scriptStatus');if(el){el.textContent=text;el.style.color=error?'#a00000':'#666';}}
function loginError(text=''){const el=$('#loginError');if(el)el.textContent=text;}
function toast(text,error=false){const el=$('#toast');if(!el)return;el.textContent=text;el.style.background=error?'#8b0000':'#111';el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3500);}
function showLogin(){$('#loginView')?.classList.remove('hidden');$('#appView')?.classList.add('hidden');}
function showPanel(user){$('#loginView')?.classList.add('hidden');$('#appView')?.classList.remove('hidden');$('#userEmail').textContent=user?.email||'';}
function withTimeout(promise,ms=15000){return Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>reject(new Error('İstek zaman aşımına uğradı.')),ms))]);}
function formObject(form){return Object.fromEntries(new FormData(form).entries());}
function emptyToNull(v){return v===''?null:v;}
function setSubmitState(form,busy,label){const btn=form.querySelector('button[type="submit"]');if(!btn)return;if(!btn.dataset.label)btn.dataset.label=btn.textContent;btn.disabled=busy;btn.textContent=busy?label:btn.dataset.label;}
async function uploadImage(file,folder){if(!file||!file.size)return null;const allowed=['image/jpeg','image/png','image/webp'];if(!allowed.includes(file.type))throw new Error('Sadece JPG, PNG veya WEBP görselleri yükleyebilirsiniz.');if(file.size>5*1024*1024)throw new Error('Görsel boyutu 5 MB sınırını aşıyor.');const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'');const path=`${folder}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error}=await db.storage.from(MEDIA_BUCKET).upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type});if(error)throw new Error('Görsel yüklenemedi: '+error.message);return db.storage.from(MEDIA_BUCKET).getPublicUrl(path).data.publicUrl;}
function ensureContactUi(){const side=document.querySelector('.side');if(side&&!side.querySelector('[data-tab="messages"]')){const btn=document.createElement('button');btn.dataset.tab='messages';btn.textContent='İletişim Mesajları';const sponsorBtn=side.querySelector('[data-tab="sponsors"]');side.insertBefore(btn,sponsorBtn||side.querySelector('a'));btn.addEventListener('click',()=>{$$('.tab').forEach(t=>t.classList.add('hidden'));$('#messages')?.classList.remove('hidden');$('#pageTitle').textContent='İletişim Mesajları';loadContactMessages();});}const main=document.querySelector('.main');if(main&&!$('#messages')){const tab=document.createElement('div');tab.id='messages';tab.className='tab hidden';tab.innerHTML='<div class="panel"><h2>İletişim Mesajları</h2><div id="contactMessageList"><p>Yükleniyor...</p></div></div>';main.appendChild(tab);}}
async function init(){try{ensureContactUi();if(!window.supabase)throw new Error('Supabase kütüphanesi yüklenemedi.');if(!cfg.url||!cfg.publishableKey)throw new Error('Supabase bağlantı ayarları eksik.');db=window.supabase.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data,error}=await withTimeout(db.auth.getSession(),10000);if(error)throw error;status('Sistem hazır');if(data.session?.user){showPanel(data.session.user);await loadAll();}else showLogin();}catch(err){showLogin();loginError(err.message||String(err));status('Bağlantı hatası',true);}}
$('#loginForm')?.addEventListener('submit',async e=>{e.preventDefault();const btn=$('#loginButton');loginError('');btn.disabled=true;btn.textContent='Giriş yapılıyor...';try{const {data,error}=await withTimeout(db.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value}),15000);if(error)throw error;if(!data.user)throw new Error('Kullanıcı bilgisi alınamadı.');showPanel(data.user);await loadAll();}catch(err){loginError('Giriş başarısız: '+(err.message||String(err)));}finally{btn.disabled=false;btn.textContent='Giriş Yap';}});
$('#logout')?.addEventListener('click',async()=>{await db.auth.signOut();showLogin();status('Sistem hazır');});$('#refresh')?.addEventListener('click',loadAll);$$('.side [data-tab]').forEach(btn=>btn.addEventListener('click',()=>{$$('.tab').forEach(t=>t.classList.add('hidden'));$('#'+btn.dataset.tab)?.classList.remove('hidden');$('#pageTitle').textContent=btn.textContent.trim();}));
async function queryOrThrow(builder){const res=await builder;if(res.error)throw res.error;return res.data||[];}
async function loadAll(){try{ensureContactUi();await Promise.all([loadSettings(),loadNews(),loadMatches(),loadPlayers(),loadApplications('academy_applications','#academyList'),loadApplications('membership_requests','#membershipList'),loadSponsors(),loadContactMessages(),loadCounts()]);}catch(err){toast(err.message||String(err),true);}}
async function loadCounts(){const tables=['news','matches','players'];const r=await Promise.all(tables.map(t=>db.from(t).select('*',{count:'exact',head:true})));$('#countNews').textContent=r[0].count||0;$('#countMatches').textContent=r[1].count||0;$('#countPlayers').textContent=r[2].count||0;const [a,u]=await Promise.all([db.from('academy_applications').select('*',{count:'exact',head:true}).eq('status','new'),db.from('membership_requests').select('*',{count:'exact',head:true}).eq('status','new')]);$('#countApps').textContent=(a.count||0)+(u.count||0);}
async function loadSettings(){const {data,error}=await db.from('site_settings').select('*').eq('id',1).maybeSingle();if(error)throw error;if(!data)return;const f=$('#settingsForm');Object.entries(data).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v??'';});}
$('#settingsForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;setSubmitState(f,true,'Kaydediliyor...');const d=formObject(f);d.club_logo_size=Number(d.club_logo_size||110);d.updated_at=new Date().toISOString();const {error}=await db.from('site_settings').update(d).eq('id',1);setSubmitState(f,false);toast(error?error.message:'Tüm içerik kaydedildi',!!error);});
function listHtml(rows,render){return rows.length?rows.map(render).join(''):'<p>Kayıt yok.</p>';}
function cache(table,rows){records[table]={};rows.forEach(r=>records[table][r.id]=r);}
function bindActions(){$$('[data-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('Silmek istediğinizden emin misiniz?'))return;const {error}=await db.from(b.dataset.delete).delete().eq('id',b.dataset.id);toast(error?error.message:'Silindi',!!error);if(!error)loadAll();});$$('[data-edit]').forEach(b=>b.onclick=()=>editRecord(b.dataset.edit,b.dataset.id));}
async function editRecord(table,id){const r=records[table]?.[id];if(!r)return;let d={};if(table==='news'){const title_tr=prompt('Türkçe başlık',r.title_tr||'');if(title_tr===null)return;const title_en=prompt('İngilizce başlık',r.title_en||'');if(title_en===null)return;const body_tr=prompt('Türkçe metin',r.body_tr||'');if(body_tr===null)return;const body_en=prompt('İngilizce metin',r.body_en||'');if(body_en===null)return;d={title_tr,title_en,body_tr,body_en,published:confirm('Haber yayında olsun mu?')};}else if(table==='matches'){const opponent=prompt('Rakip',r.opponent||'');if(opponent===null)return;const venue=prompt('Salon',r.venue||'');if(venue===null)return;const statusValue=prompt('Durum: upcoming / finished / cancelled',r.status||'upcoming');if(statusValue===null)return;const ticket_url=prompt('Bilet bağlantısı',r.ticket_url||'');if(ticket_url===null)return;const home=prompt('Ev skoru (boş bırakılabilir)',r.home_score??'');if(home===null)return;const away=prompt('Deplasman skoru (boş bırakılabilir)',r.away_score??'');if(away===null)return;d={opponent,venue,status:statusValue,ticket_url,home_score:home===''?null:Number(home),away_score:away===''?null:Number(away)};}else if(table==='players'){const name=prompt('Ad Soyad',r.name||'');if(name===null)return;const number=prompt('Forma No',r.number??'');if(number===null)return;const position_tr=prompt('Pozisyon TR',r.position_tr||'');if(position_tr===null)return;const position_en=prompt('Pozisyon EN',r.position_en||'');if(position_en===null)return;d={name,number:number===''?null:Number(number),position_tr,position_en,active:confirm('Oyuncu aktif olsun mu?')};}else if(table==='sponsors'){const name=prompt('Sponsor adı',r.name||'');if(name===null)return;const website_url=prompt('Web sitesi',r.website_url||'');if(website_url===null)return;const sort_order=prompt('Sıra',r.sort_order??0);if(sort_order===null)return;d={name,website_url,sort_order:Number(sort_order||0)};}const {error}=await db.from(table).update(d).eq('id',id);toast(error?error.message:'Değişiklikler kaydedildi',!!error);if(!error)loadAll();}
async function loadNews(){const data=await queryOrThrow(db.from('news').select('*').order('published_at',{ascending:false}));cache('news',data);$('#newsList').innerHTML=listHtml(data,n=>`<div class="card"><strong>${esc(n.title_tr)}</strong>${n.image_url?`<img class="thumb" src="${esc(n.image_url)}" alt="">`:''}<p>${esc(n.body_tr||'')}</p><small>${n.published?'Yayında':'Taslak'}</small><div class="actions"><button class="btn dark" data-edit="news" data-id="${n.id}">Düzenle</button><button class="btn danger" data-delete="news" data-id="${n.id}">Sil</button></div></div>`);bindActions();}
$('#newsForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;setSubmitState(f,true,'Yükleniyor...');try{const d=formObject(f);delete d.image_file;d.image_url=await uploadImage(f.elements.image_file.files[0],'news');d.published=f.elements.published.checked;d.published_at=new Date().toISOString();const {error}=await db.from('news').insert(d);if(error)throw error;toast('Haber eklendi');f.reset();await loadAll();}catch(err){toast(err.message||String(err),true);}finally{setSubmitState(f,false);}});
async function loadMatches(){const data=await queryOrThrow(db.from('matches').select('*').order('match_date',{ascending:false}));cache('matches',data);$('#matchList').innerHTML=listHtml(data,m=>`<div class="card"><strong>${esc(m.opponent)}</strong>${m.opponent_logo_url?`<img class="thumb" src="${esc(m.opponent_logo_url)}" alt="${esc(m.opponent)}">`:''}<p>${new Date(m.match_date).toLocaleString('tr-TR')} · ${esc(m.venue||'')}</p>${m.ticket_url?`<p><a href="${esc(m.ticket_url)}" target="_blank" rel="noopener">Bilet bağlantısı</a></p>`:''}<small>${esc(m.status)}</small><div class="actions"><button class="btn dark" data-edit="matches" data-id="${m.id}">Düzenle</button><button class="btn danger" data-delete="matches" data-id="${m.id}">Sil</button></div></div>`);bindActions();}
$('#matchForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;setSubmitState(f,true,'Yükleniyor...');try{const d=formObject(f);delete d.opponent_logo_file;d.opponent_logo_url=await uploadImage(f.elements.opponent_logo_file.files[0],'matches');d.match_date=new Date(d.match_date).toISOString();d.home_score=emptyToNull(d.home_score)==null?null:Number(d.home_score);d.away_score=emptyToNull(d.away_score)==null?null:Number(d.away_score);d.ticket_url=d.ticket_url||null;const {error}=await db.from('matches').insert(d);if(error)throw error;toast('Maç, rakip logosu ve bilet bağlantısı eklendi');f.reset();await loadAll();}catch(err){toast(err.message||String(err),true);}finally{setSubmitState(f,false);}});
async function loadPlayers(){const data=await queryOrThrow(db.from('players').select('*').order('number'));cache('players',data);$('#playerList').innerHTML=listHtml(data,p=>`<div class="card"><strong>${esc(p.number??'')} ${esc(p.name)}</strong>${p.image_url?`<img class="thumb" src="${esc(p.image_url)}" alt="">`:''}<p>${esc(p.position_tr||'')}</p><small>${p.active?'Aktif':'Pasif'}</small><div class="actions"><button class="btn dark" data-edit="players" data-id="${p.id}">Düzenle</button><button class="btn danger" data-delete="players" data-id="${p.id}">Sil</button></div></div>`);bindActions();}
$('#playerForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;setSubmitState(f,true,'Yükleniyor...');try{const d=formObject(f);delete d.image_file;d.image_url=await uploadImage(f.elements.image_file.files[0],'players');d.number=emptyToNull(d.number)==null?null:Number(d.number);d.active=f.elements.active.checked;const {error}=await db.from('players').insert(d);if(error)throw error;toast('Oyuncu eklendi');f.reset();await loadAll();}catch(err){toast(err.message||String(err),true);}finally{setSubmitState(f,false);}});
async function loadApplications(table,target){const data=await queryOrThrow(db.from(table).select('*').order('created_at',{ascending:false}));$(target).innerHTML=listHtml(data,a=>`<div class="card"><strong>${esc(a.full_name)}</strong><p>${esc(a.email)} · ${esc(a.phone||'')}</p><p>${esc(a.age_group||a.reason||'')}</p><select data-status-table="${table}" data-id="${a.id}"><option value="new" ${a.status==='new'?'selected':''}>Yeni</option><option value="reviewing" ${a.status==='reviewing'?'selected':''}>İnceleniyor</option><option value="accepted" ${a.status==='accepted'?'selected':''}>Kabul</option><option value="rejected" ${a.status==='rejected'?'selected':''}>Red</option></select></div>`);$$('[data-status-table]').forEach(s=>s.onchange=async()=>{const {error}=await db.from(s.dataset.statusTable).update({status:s.value}).eq('id',s.dataset.id);toast(error?error.message:'Durum güncellendi',!!error);});}
async function loadSponsors(){const data=await queryOrThrow(db.from('sponsors').select('*').order('sort_order'));cache('sponsors',data);$('#sponsorList').innerHTML=listHtml(data,s=>`<div class="card"><strong>${esc(s.name)}</strong>${s.logo_url?`<img class="thumb" src="${esc(s.logo_url)}" alt="">`:''}<p>${esc(s.website_url||'')}</p><div class="actions"><button class="btn dark" data-edit="sponsors" data-id="${s.id}">Düzenle</button><button class="btn danger" data-delete="sponsors" data-id="${s.id}">Sil</button></div></div>`);bindActions();}
$('#sponsorForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;setSubmitState(f,true,'Yükleniyor...');try{const d=formObject(f);delete d.image_file;d.logo_url=await uploadImage(f.elements.image_file.files[0],'sponsors');d.sort_order=Number(d.sort_order||0);d.active=true;const {error}=await db.from('sponsors').insert(d);if(error)throw error;toast('Sponsor eklendi');f.reset();await loadAll();}catch(err){toast(err.message||String(err),true);}finally{setSubmitState(f,false);}});
async function loadContactMessages(){const target=$('#contactMessageList');if(!target||!db)return;const {data,error}=await db.from('contact_messages').select('*').order('created_at',{ascending:false});if(error){target.innerHTML=`<p style="color:#a00000">${esc(error.message)}</p>`;return;}target.innerHTML=listHtml(data||[],m=>`<div class="card"><strong>${esc(m.full_name)}</strong><p><a href="mailto:${esc(m.email)}">${esc(m.email)}</a> · ${new Date(m.created_at).toLocaleString('tr-TR')}</p><p style="white-space:pre-wrap">${esc(m.message)}</p><div class="actions"><select data-message-status data-id="${m.id}"><option value="new" ${m.status==='new'?'selected':''}>Yeni</option><option value="read" ${m.status==='read'?'selected':''}>Okundu</option><option value="replied" ${m.status==='replied'?'selected':''}>Yanıtlandı</option><option value="archived" ${m.status==='archived'?'selected':''}>Arşiv</option></select><a class="btn primary" href="mailto:${esc(m.email)}?subject=Karagümrük Hentbol">E-posta ile Yanıtla</a><button class="btn danger" data-message-delete data-id="${m.id}">Sil</button></div></div>`);$$('[data-message-status]').forEach(s=>s.onchange=async()=>{const {error}=await db.from('contact_messages').update({status:s.value}).eq('id',s.dataset.id);toast(error?error.message:'Mesaj durumu güncellendi',!!error);});$$('[data-message-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('Mesaj silinsin mi?'))return;const {error}=await db.from('contact_messages').delete().eq('id',b.dataset.id);toast(error?error.message:'Mesaj silindi',!!error);if(!error)loadContactMessages();});}
init();