(()=>{
 const cfg=window.KH_SUPABASE||{};let db,loading=false;
 const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
 async function invoke(action,id){const {data,error}=await db.functions.invoke('ticket-admin-action',{body:{action,id}});if(error)throw error;if(!data?.ok)throw new Error(data?.error||'İşlem başarısız');return data;}
 async function accept(id,b){if(!confirm('Bilet onaylanıp PDF olarak gönderilsin mi?'))return;b.disabled=true;try{await invoke('accept',id);alert('Bilet gönderildi.');await render();}catch(e){alert('Hata: '+(e.message||e));b.disabled=false;}}
 async function remove(id){if(!confirm('Talep silinsin mi?'))return;const {error}=await db.from('ticket_requests').delete().eq('id',id);if(error)alert(error.message);else render();}
 async function configureMatch(id){const {data:m,error}=await db.from('matches').select('*').eq('id',id).single();if(error)return alert(error.message);const enabled=confirm('Bu maç için bilet talebi açık olsun mu?');let capacity=m.ticket_capacity||'';let competition=m.competition||'';if(enabled){capacity=prompt('Maksimum kapasite (boş bırakılabilir)',capacity);if(capacity===null)return;competition=prompt('Organizasyon / Lig adı',competition);if(competition===null)return;}const {error:u}=await db.from('matches').update({tickets_enabled:enabled,ticket_capacity:capacity===''?null:Number(capacity),competition:competition||null}).eq('id',id);alert(u?u.message:'Bilet ayarları kaydedildi.');decorateMatches();}
 async function decorateMatches(){const cards=document.querySelectorAll('#matchList .card');const {data}=await db.from('matches').select('id,opponent,tickets_enabled,ticket_capacity,competition').order('match_date',{ascending:false});if(!data)return;cards.forEach((card,i)=>{const m=data[i];if(!m||card.querySelector('[data-ticket-config]'))return;const p=document.createElement('p');p.innerHTML=`Bilet: <b>${m.tickets_enabled?'Açık':'Kapalı'}</b>${m.ticket_capacity?` · Kapasite: ${m.ticket_capacity}`:''}`;card.appendChild(p);const actions=card.querySelector('.actions')||card;const btn=document.createElement('button');btn.className='btn primary';btn.dataset.ticketConfig=m.id;btn.textContent='Bilet Ayarları';btn.onclick=()=>configureMatch(m.id);actions.prepend(btn);});}
 async function render(){const list=document.querySelector('#ticketRequestList');if(!list||loading)return;loading=true;const {data,error}=await db.from('ticket_requests').select('*,matches(*)').order('created_at',{ascending:false});if(error){list.innerHTML='<p>'+esc(error.message)+'</p>';loading=false;return;}list.innerHTML=data?.length?data.map(r=>`<div class="card"><strong>${esc(r.full_name)}</strong><p>${esc(r.email)} · ${esc(r.phone)}</p><p>${esc(r.matches?.opponent||'Maç')} · ${r.matches?.match_date?new Date(r.matches.match_date).toLocaleString('tr-TR'):''}</p><small>Durum: <b>${r.status==='accepted'?'Kabul Edildi':'Yeni'}</b>${r.ticket_number?' · '+esc(r.ticket_number):''}</small><div class="actions">${r.status==='accepted'?'<button class="btn primary" disabled>Gönderildi</button>':`<button class="btn primary" data-ticket-accept="${r.id}">Kabul Et ve Gönder</button>`}<button class="btn danger" data-ticket-delete="${r.id}">Sil</button></div></div>`).join(''):'<p>Bilet talebi yok.</p>';list.querySelectorAll('[data-ticket-accept]').forEach(b=>b.onclick=()=>accept(b.dataset.ticketAccept,b));list.querySelectorAll('[data-ticket-delete]').forEach(b=>b.onclick=()=>remove(b.dataset.ticketDelete));loading=false;}
 function openTab(){document.querySelectorAll('#appView .tab').forEach(t=>t.classList.add('hidden'));document.querySelector('#ticketRequests')?.classList.remove('hidden');const title=document.querySelector('#pageTitle');if(title)title.textContent='Bilet Talepleri';render();}
 function start(){if(!window.supabase||!cfg.url||!cfg.publishableKey)return setTimeout(start,300);db=window.supabase.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true}});const app=document.querySelector('#appView');if(!app)return setTimeout(start,400);const side=app.querySelector('.side');let btn=side?.querySelector('[data-tab="ticketRequests"]');if(side&&!btn){btn=document.createElement('button');btn.dataset.tab='ticketRequests';btn.textContent='Bilet Talepleri';side.insertBefore(btn,side.querySelector('[data-tab="sponsors"]')||side.querySelector('a'));}const main=app.querySelector('.main');if(main&&!document.querySelector('#ticketRequests')){const tab=document.createElement('div');tab.id='ticketRequests';tab.className='tab hidden';tab.innerHTML='<div class="panel"><h2>Bilet Talepleri</h2><div id="ticketRequestList"></div></div>';main.appendChild(tab);}if(btn&&!btn.dataset.bound){btn.dataset.bound='1';btn.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();openTab();});}setTimeout(decorateMatches,1200);setInterval(()=>{decorateMatches();if(!document.querySelector('#ticketRequests')?.classList.contains('hidden'))render();},5000);}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();