const fallbackNews=[{published_at:'2026-07-18',title_tr:'Yeni sezon hazırlıkları başladı',title_en:'Pre-season preparations have begun',body_tr:'Takımımız yeni sezon için ilk antrenmanını gerçekleştirdi.',body_en:'Our team held its first training session for the new season.'}];
const DEFAULT_SETTINGS={club_logo_size:110,hero_title_tr:'KARAGÜMRÜK HENTBOL',hero_title_en:'KARAGÜMRÜK HANDBALL',hero_eyebrow_tr:'Sahada kalp, tribünde güç',hero_eyebrow_en:'Heart on the court, strength in the stands'};
let currentLang=localStorage.getItem('siteLang')||'tr',cmsNews=fallbackNews,db=null,currentMatch=null,cmsSponsors=[];
const cfg=window.KH_SUPABASE||{};
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const langValue=(s,key)=>s[`${key}_${currentLang}`]||'';
function setBilingual(el,tr,en){if(!el)return;el.dataset.tr=tr||'';el.dataset.en=en||'';el.textContent=currentLang==='tr'?(tr||''):(en||'');}
function renderNews(){const g=document.getElementById('newsGrid');if(!g)return;g.innerHTML=cmsNews.slice(0,6).map(n=>`<article class="news-card">${n.image_url?`<img class="news-image" src="${esc(n.image_url)}" alt="">`:'<div class="news-image"></div>'}<div class="news-body"><time>${new Date(n.published_at||n.created_at||Date.now()).toLocaleDateString(currentLang==='tr'?'tr-TR':'en-GB')}</time><h3>${esc(currentLang==='tr'?n.title_tr:n.title_en)}</h3><p>${esc(currentLang==='tr'?(n.body_tr||''):(n.body_en||''))}</p></div></article>`).join('');}
function renderSponsors(){const section=document.querySelector('.sponsor-section');if(!section)return;const container=section.querySelector('.container');if(!container)return;let grid=document.getElementById('sponsorsGrid');if(!grid){grid=document.createElement('div');grid.id='sponsorsGrid';grid.style.cssText='display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:22px;align-items:stretch;margin-top:28px';container.appendChild(grid);}if(!cmsSponsors.length){grid.innerHTML='<p style="grid-column:1/-1;text-align:center;color:#666">'+(currentLang==='tr'?'Sponsorlar yakında burada görünecek.':'Sponsors will appear here soon.')+'</p>';return;}grid.innerHTML=cmsSponsors.map(s=>{const card=`<div style="height:100%;min-height:170px;background:#fff;border:1px solid #e6e6e6;border-radius:12px;padding:22px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:14px;box-shadow:0 10px 28px rgba(0,0,0,.08)">${s.logo_url?`<img src="${esc(s.logo_url)}" alt="${esc(s.name)}" style="width:100%;height:95px;object-fit:contain">`:''}<strong style="font:700 23px 'Barlow Condensed',sans-serif;text-align:center;color:#111">${esc(s.name)}</strong></div>`;return s.website_url?`<a href="${esc(s.website_url)}" target="_blank" rel="noopener" style="text-decoration:none">${card}</a>`:card;}).join('');}
function setLang(l){currentLang=l;document.documentElement.lang=l;document.querySelectorAll('[data-tr]').forEach(e=>{if(e.dataset[l]!==undefined)e.textContent=e.dataset[l]});document.querySelectorAll('.lang-btn').forEach(b=>b.classList.toggle('active',b.dataset.lang===l));localStorage.setItem('siteLang',l);renderNews();renderSponsors();applySettings(window.__settings||DEFAULT_SETTINGS);if(currentMatch)renderMatch(currentMatch);}
function applyHeroText(s){const h=document.querySelector('.hero h1');if(h){const t=langValue(s,'hero_title')||DEFAULT_SETTINGS[`hero_title_${currentLang}`],p=t.split(' ');h.innerHTML=`<span>${esc(p.slice(0,-1).join(' ')||p[0]||'')}</span><strong>${esc(p.length>1?p.at(-1):'')}</strong>`}const x=document.querySelector('.hero-text');if(x&&langValue(s,'hero_text'))x.textContent=langValue(s,'hero_text');const eyebrow=document.querySelector('.hero .eyebrow');setBilingual(eyebrow,s.hero_eyebrow_tr||DEFAULT_SETTINGS.hero_eyebrow_tr,s.hero_eyebrow_en||DEFAULT_SETTINGS.hero_eyebrow_en);}
function applySettings(r){const s={...DEFAULT_SETTINGS,...r};window.__settings=s;const logo=document.querySelector('.brand img');if(logo)logo.style.width=logo.style.height=`${s.club_logo_size||110}px`;applyHeroText(s);
const club=document.querySelector('#club');if(club){setBilingual(club.querySelector('h2'),s.club_title_tr||'Karagümrük Ruhuyla',s.club_title_en||'The Karagümrük Spirit');setBilingual(club.querySelector('p'),s.club_about_tr||'',s.club_about_en||'');const founded=club.querySelector('.stats div:first-child strong');if(founded&&s.founded_year)founded.textContent=s.founded_year;let extra=club.querySelector('.club-extra');if(!extra){extra=document.createElement('div');extra.className='club-extra';club.appendChild(extra)}extra.innerHTML=['vision','mission','goals'].map(k=>langValue(s,k)?`<div><h3>${currentLang==='tr'?({vision:'Vizyon',mission:'Misyon',goals:'Hedefler'}[k]):({vision:'Vision',mission:'Mission',goals:'Goals'}[k])}</h3><p>${esc(langValue(s,k))}</p></div>`:'').join('');}
const academy=document.querySelector('#academy');if(academy){setBilingual(academy.querySelector('h2'),s.academy_title_tr||'Karagümrük Hentbol Akademisi',s.academy_title_en||'Karagümrük Handball Academy');setBilingual(academy.querySelector('div>p'),s.academy_text_tr||'',s.academy_text_en||'');}
const membership=document.querySelector('#membership');if(membership){setBilingual(membership.querySelector('h2'),s.membership_title_tr||'Üyelik',s.membership_title_en||'Membership');let intro=membership.querySelector('.membership-intro');if(!intro){intro=document.createElement('p');intro.className='membership-intro';membership.querySelector('.membership-grid>div')?.insertBefore(intro,membership.querySelector('.membership-grid>div h3'));}setBilingual(intro,s.membership_text_tr||'',s.membership_text_en||'');const conditions=(langValue(s,'membership_conditions')||'').split('\n').map(x=>x.trim()).filter(Boolean);const list=membership.querySelector('.conditions');if(list&&conditions.length)list.innerHTML=conditions.map(x=>`<li>${esc(x)}</li>`).join('');}
const donate=document.querySelector('#donate');if(donate){setBilingual(donate.querySelector('h2'),s.donation_title_tr||'Kulübe Destek Ol',s.donation_title_en||'Support the Club');setBilingual(donate.querySelector('.donate-box>div p'),s.donation_text_tr||'',s.donation_text_en||'');const a=donate.querySelector('.donate-actions a');if(a&&s.donation_link){a.href=s.donation_link;a.target='_blank'}const note=donate.querySelector('.donate-actions small');if(note&&s.donation_iban)note.textContent=`IBAN: ${s.donation_iban}`;}
const contact=document.querySelector('#contact .contact-grid>div');if(contact){const ps=contact.querySelectorAll(':scope>p');if(ps[0]&&s.contact_email)ps[0].textContent=s.contact_email;if(ps[1]&&s.contact_address)ps[1].textContent=s.contact_address;let details=contact.querySelector('.contact-details');if(!details){details=document.createElement('div');details.className='contact-details';contact.appendChild(details)}const links=[['Telefon',s.contact_phone,s.contact_phone?`tel:${s.contact_phone.replace(/\s/g,'')}`:''],['WhatsApp',s.whatsapp_url,s.whatsapp_url],['Instagram',s.instagram_url,s.instagram_url],['Facebook',s.facebook_url,s.facebook_url],['YouTube',s.youtube_url,s.youtube_url],['X',s.twitter_url,s.twitter_url],['Konum',s.maps_url,s.maps_url]].filter(x=>x[1]);details.innerHTML=links.map(([label,text,url])=>`<p><strong>${esc(label)}:</strong> ${url?`<a href="${esc(url)}" target="_blank" rel="noopener">${esc(text)}</a>`:esc(text)}</p>`).join('');}}
function renderMatch(m){currentMatch=m;const c=document.querySelector('.match-card');if(!c)return;const d=new Date(m.match_date),ticketLabel=currentLang==='tr'?'Bilet Satın Al':'Buy Tickets',ticketHref=m.ticket_url||'#contact',ticketTarget=m.ticket_url?' target="_blank" rel="noopener"':'';c.innerHTML=`<div class="match-teams"><div class="team-logo"><img src="assets/club-logo.png" alt="Karagümrük"></div><strong>VS</strong><div class="opponent">${m.opponent_logo_url?`<img src="${esc(m.opponent_logo_url)}" alt="${esc(m.opponent)}" style="width:86px;height:86px;object-fit:contain;display:block;margin:0 auto 8px">`:''}${esc(m.opponent)}</div></div><div class="match-meta"><span>📅 ${d.toLocaleDateString(currentLang==='tr'?'tr-TR':'en-GB')}</span><span>🕔 ${d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span><span>📍 ${esc(m.venue||'')}</span></div><div style="margin-top:22px;text-align:center"><a href="${esc(ticketHref)}"${ticketTarget} aria-label="${ticketLabel}" style="display:inline-flex;align-items:center;justify-content:center;gap:10px;min-width:230px;padding:16px 30px;border-radius:8px;background:#e10600;color:#fff;font-weight:800;font-size:15px;text-transform:uppercase;text-decoration:none;box-shadow:0 10px 24px rgba(225,6,0,.32)">🎟️ <span>${ticketLabel}</span></a></div>`;}
function renderPlayers(ps){const g=document.querySelector('.players-grid');if(!g)return;g.innerHTML=ps.map(p=>`<article class="player">${p.image_url?`<img class="player-photo" src="${esc(p.image_url)}" alt="${esc(p.name)}">`:`<div class="player-photo">${esc(p.number??'')}</div>`}<h3>${esc(p.name)}</h3><p>${esc(currentLang==='tr'?(p.position_tr||''):(p.position_en||''))}</p></article>`).join('');}
async function submitForm(t,p,f){if(!db)return alert('Bağlantı hazırlanıyor, tekrar deneyin.');const b=f.querySelector('button[type=submit]');b.disabled=true;const {error}=await db.from(t).insert(p);b.disabled=false;if(error)return alert('Gönderilemedi: '+error.message);f.reset();alert(currentLang==='tr'?'Başvurunuz alındı.':'Your application was received.');}
async function uploadMemberPhoto(file){if(!file)throw new Error(currentLang==='tr'?'Fotoğraf seçiniz.':'Please select a photo.');if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error(currentLang==='tr'?'Sadece JPG, PNG veya WEBP yükleyebilirsiniz.':'Only JPG, PNG or WEBP files are allowed.');if(file.size>5*1024*1024)throw new Error(currentLang==='tr'?'Fotoğraf en fazla 5 MB olabilir.':'The photo must be 5 MB or smaller.');const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'');const path=`membership-photos/${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error}=await db.storage.from('site-media').upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type});if(error)throw error;return db.storage.from('site-media').getPublicUrl(path).data.publicUrl;}
async function submitMembership(f){if(!db)return alert(currentLang==='tr'?'Bağlantı hazırlanıyor, tekrar deneyin.':'Connection is being prepared, please try again.');const b=f.querySelector('button[type=submit]');b.disabled=true;try{const photoUrl=await uploadMemberPhoto(f.elements.photo.files[0]);const payload={full_name:f.elements.full_name.value.trim(),email:f.elements.email.value.trim(),phone:f.elements.phone.value.trim(),reason:f.elements.reason.value.trim(),photo_url:photoUrl,status:'new'};const {error}=await db.from('membership_requests').insert(payload);if(error)throw error;const {error:mailError}=await db.functions.invoke('send-membership-email',{body:{...payload,lang:currentLang}});f.reset();if(mailError){console.error('Membership confirmation email failed:',mailError);return alert(currentLang==='tr'?'Başvurunuz alındı. Onay e-postası kısa süre içinde gönderilecektir.':'Your application was received. The confirmation email will be sent shortly.');}alert(currentLang==='tr'?'Başvurunuz alındı. E-postanıza onay mesajı gönderildi.':'Your application was received. A confirmation email was sent to you.');}catch(error){alert((currentLang==='tr'?'Başvuru gönderilemedi: ':'Application could not be sent: ')+(error.message||String(error)));}finally{b.disabled=false;}}
async function loadCms(){if(!db){applySettings(DEFAULT_SETTINGS);renderNews();renderSponsors();return}const [s,n,m,p,sp]=await Promise.all([db.from('site_settings').select('*').eq('id',1).maybeSingle(),db.from('news').select('*').eq('published',true).order('published_at',{ascending:false}).limit(6),db.from('matches').select('*').eq('status','upcoming').order('match_date',{ascending:true}).limit(1),db.from('players').select('*').eq('active',true).order('number').limit(8),db.from('sponsors').select('*').order('sort_order',{ascending:true})]);applySettings(s.data||DEFAULT_SETTINGS);if(n.data?.length)cmsNews=n.data;cmsSponsors=(sp.data||[]).filter(x=>x.active!==false);renderNews();renderSponsors();if(m.data?.[0])renderMatch(m.data[0]);if(p.data?.length)renderPlayers(p.data);}
function loadSdk(){return new Promise((resolve,reject)=>{if(window.supabase)return resolve();const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)});}
document.querySelectorAll('.lang-btn').forEach(b=>b.addEventListener('click',()=>setLang(b.dataset.lang)));document.querySelector('.menu-toggle')?.addEventListener('click',()=>document.querySelector('.main-nav')?.classList.toggle('open'));
document.getElementById('academyForm')?.addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget;submitForm('academy_applications',{full_name:f.elements[0].value,email:f.elements[1].value,phone:f.elements[2].value,age_group:f.elements[3].value},f)});
document.getElementById('membershipForm')?.addEventListener('submit',e=>{e.preventDefault();submitMembership(e.currentTarget)});
document.getElementById('contactForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;if(!db)return alert(currentLang==='tr'?'Bağlantı hazırlanıyor, tekrar deneyin.':'Connection is being prepared, please try again.');const btn=f.querySelector('button[type=submit]');btn.disabled=true;const payload={full_name:f.elements[0].value.trim(),email:f.elements[1].value.trim(),message:f.elements[2].value.trim(),status:'new',source:'website'};const {error}=await db.from('contact_messages').insert(payload);btn.disabled=false;if(error)return alert((currentLang==='tr'?'Mesaj gönderilemedi: ':'Message could not be sent: ')+error.message);f.reset();alert(currentLang==='tr'?'Mesajınız kulübe ulaştı.':'Your message was delivered to the club.');});
setLang(currentLang);loadSdk().then(()=>{db=window.supabase.createClient(cfg.url,cfg.publishableKey);loadCms()}).catch(()=>{applySettings(DEFAULT_SETTINGS);renderNews();renderSponsors()});