(()=>{
 const cfg=window.KH_SUPABASE||{};let db;
 const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
 const css=`<style>#tickets{background:#0e0e0e;color:#fff}.ticket-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:22px}.ticket-match{background:#181818;border:1px solid #333;border-radius:18px;padding:22px;text-align:center}.ticket-logos{display:flex;align-items:center;justify-content:center;gap:24px;margin:16px 0}.ticket-logos img{width:82px;height:82px;object-fit:contain}.ticket-meta{display:grid;gap:7px;color:#ddd;margin:15px 0}.ticket-modal{position:fixed;inset:0;background:#000b;display:none;align-items:center;justify-content:center;z-index:9999;padding:18px}.ticket-modal.show{display:flex}.ticket-box{width:min(520px,100%);background:#fff;color:#111;border-radius:18px;padding:26px;position:relative}.ticket-box input{width:100%;box-sizing:border-box;margin:7px 0;padding:13px;border:1px solid #bbb;border-radius:10px}.ticket-close{position:absolute;right:15px;top:12px;border:0;background:none;font-size:26px}.ticket-note{min-height:24px;font-weight:700}</style>`;
 async function load(){const host=document.querySelector('#matches');if(!host||!db)return;let sec=document.querySelector('#tickets');if(!sec){sec=document.createElement('section');sec.id='tickets';sec.className='section';sec.innerHTML=`<div class="container"><div class="section-heading"><div><span class="section-kicker">Tribünde yerini al</span><h2>Maç Biletleri</h2></div></div><div id="ticketMatches" class="ticket-grid"><p>Yükleniyor...</p></div></div>`;host.insertAdjacentElement('afterend',sec);document.head.insertAdjacentHTML('beforeend',css);document.body.insertAdjacentHTML('beforeend',`<div class="ticket-modal" id="ticketModal"><div class="ticket-box"><button class="ticket-close" type="button">×</button><h3>Bilet Talebi</h3><p id="ticketMatchName"></p><form id="ticketForm"><input name="full_name" required placeholder="Ad Soyad"><input name="email" type="email" required placeholder="E-posta"><input name="phone" required placeholder="Telefon"><input name="match_id" type="hidden"><button class="btn btn-primary" type="submit">Talebi Gönder</button><p class="ticket-note" id="ticketNote"></p></form></div></div>`);bind();}
 const {data,error}=await db.from('matches').select('*').eq('tickets_enabled',true).eq('status','upcoming').order('match_date');const grid=document.querySelector('#ticketMatches');if(error){grid.innerHTML='<p>Biletler yüklenemedi.</p>';return;}if(!data?.length){grid.innerHTML='<p>Şu anda satışa açık maç bileti bulunmuyor.</p>';return;}grid.innerHTML=data.map(m=>`<article class="ticket-match"><div class="ticket-logos"><img src="assets/club-logo.png" alt="Karagümrük"><strong>VS</strong><img src="${esc(m.opponent_logo_url||'assets/club-logo.png')}" alt="${esc(m.opponent)}"></div><h3>Karagümrük – ${esc(m.opponent)}</h3><div class="ticket-meta"><span>🏆 ${esc(m.competition||'Hentbol Maçı')}</span><span>📅 ${new Date(m.match_date).toLocaleDateString('tr-TR')}</span><span>🕒 ${new Date(m.match_date).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'})}</span><span>📍 ${esc(m.venue||'İstanbul')}</span></div><button class="btn btn-primary" data-ticket-match="${m.id}" data-ticket-title="Karagümrük – ${esc(m.opponent)}">Bilet Talebi</button></article>`).join('');document.querySelectorAll('[data-ticket-match]').forEach(b=>b.onclick=()=>open(b.dataset.ticketMatch,b.dataset.ticketTitle));}
 function open(id,title){document.querySelector('#ticketForm [name=match_id]').value=id;document.querySelector('#ticketMatchName').textContent=title;document.querySelector('#ticketNote').textContent='';document.querySelector('#ticketModal').classList.add('show');}
 function bind(){const modal=document.querySelector('#ticketModal');modal.querySelector('.ticket-close').onclick=()=>modal.classList.remove('show');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('show')};document.querySelector('#ticketForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,btn=f.querySelector('button');btn.disabled=true;const d=Object.fromEntries(new FormData(f));const {error}=await db.from('ticket_requests').insert(d);document.querySelector('#ticketNote').textContent=error?'Hata: '+error.message:'Talebiniz alındı. Kulüp sizinle iletişime geçecektir.';if(!error)f.reset();btn.disabled=false;};}
 function start(){if(!window.supabase||!cfg.url||!cfg.publishableKey)return setTimeout(start,300);db=window.supabase.createClient(cfg.url,cfg.publishableKey);load();}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();